### ISSUE TITLE
Is there an truly offline solution for this?

### ISSUE THREAD

**Issue by remmi11** [klokantech/mapbox-gl-js-offline-example#1]
From the readme...
This is an example of hosting vector tiles with custom style and a local copy of MapBox GL JS library on your own server.

On my own server is still online? Is there a configuration for hosting completely offiline?

**Comment by klokan** [comment]
This is a completely offline solution.

If you speak about running the web on file:// protocol - this is not allowed in web browsers unless you explicitly permit this.

For more details check:
https://github.com/webglearth/webglearth2-offline/issues/1
