### ISSUE TITLE
Generating the pbf

### ISSUE THREAD

**Issue by DylanMoriarty** [klokantech/mapbox-gl-js-offline-example#4]
@klokan, love the work you've done here- it's been a great help for myself in trying to set up an offline mb gl map.

I was wondering what steps you took to generate the multi-layered pbf directory here. In particular what commands you ran to get from the .mbtiles to the pbf directory.

I'm currently running `mb-util [output].mbtiles [input] --image_format=pbf`, but the end result keeps kicking errors unfortunately. I'd much appreciate it if you could point to any potential things I'm missing at that step.

Thanks in advance.

**Comment by bean-fidhleir** [comment]
What errors are you seeing?  I'm in the process of unpacking mbtiles right now, and am not seeing any errors so far.  I did have a big error at first, when mb-util failed to run because it couldn't find _sqlite3, but that was the only one.  So far.

**Comment by klokan** [comment]
See:
https://github.com/klokantech/vector-tiles-sample#host-the-vector-tiles-without-any-server-at-all
